import Head from "next/head";

const getUserDetails = (id) => {
  return new Promise(async (resolve) => {
    const res = await fetch(`https://reqres.in/api/users/${id}`);
    const details = await res.json();
    console.log("getUserDetails", details, id);
    setTimeout(() => {
      resolve(details);
    }, 3000);
  });
};

export async function getServerSideProps(context) {
  const id = context.query.id;
  // Fetch data from external API
  const user = await getUserDetails(id);
  // Pass data to the page via props
  return { props: { user } };
}

export default function UserDetails({ user }) {
  const data = user?.data || [];
  console.log("UserDetails", data);
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          height: "70vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div style={{ padding: "40px", border: "1px solid #d9d9d9" }}>
          <img src={data.avatar} />
          <h4>
            {data.first_name} {data.last_name}
          </h4>
          <div>{data.email}</div>
        </div>
      </div>
    </>
  );
}
